### ISSUE TITLE
goto-line  with negative number not working

### ISSUE THREAD

**Issue by kodiakz** [m00natic/vlfi#30]
If i try to reach the end of a buffer in vlf-mode using `vlf-goto-line` with value `-1` I get the following:

> Wrong type argument: number-or-marker-p, nil

**Comment by m00natic** [comment]
Thanks for reporting!  This seems to have appeared with GNU Emacs 25.1
onwards where defvar without value provided now binds it to nil (where
before, the symbol would still be unbound).  This is needed in order
to temporarily lower tramp log level when tramp is loaded and not do
anything otherwise.  I've pushed a fix and should be OK now.
