### ISSUE TITLE
Resulting file is padded

### ISSUE THREAD

**Issue by mgsergio** [m00natic/vlfi#38]
Hi!

Is it necessary to have a resulting file padded with spaces or is it just a bug?
I have a long xml file. After saving it I have 58 spaces at the end.

vlf is cool! Saves a lot of time and nerves:)

**Comment by m00natic** [comment]
I suppose you have deleted or reduced content size.  Unfortunately
there's no obvious cross-platform way to truncate file in place (and
GNU Emacs doesn't provide such operation understandably) beyond
(loading the whole, shrinking and then) saving the whole content anew.
VLF doesn't want to go this way because of dealing with supposedly
large files and instead overwrites the remaining part of the file with
spaces.

This way, If for example, 100GB files is edited near the end, the save
would be almost instant.  In any case, it wouldn't have to load the
whole at once.  If it has to load all 100GB, the whole purpose of VLF
is gone.

So it's like this by design.  Kind of ugly, no doubt.  If portable
file truncation pops out, I'd gladly take advantage.
